version: "3.8"
services:
    pool-server:
        build: .
        ports:
            - "8000:8080"
        networks:
            - pool
            - auth

    pool-redis:
        image: "redis:alpine"
        ports:
            - "6380:6379"
        env_file:
            - .env
        command: [ "redis-server", "--requirepass ${REDIS_PASSWORD}" ]
        volumes:
            - "pool_redis_data:/data"
        healthcheck:
            test: "redis-cli -h 127.0.0.1:6379 ping"
            interval: 3s
            timeout: 1s
            retries: 5
        networks:
            - pool
            - auth

networks:
    pool:
        external: true
        driver: bridge
    auth:
        external: true
        driver: bridge

volumes:
    pool_redis_data: